# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'db_table': 'aboutus',
                'verbose_name': 'Aboutus',
                'verbose_name_plural': 'Aboutus',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'city',
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'country',
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.SmallIntegerField(blank=True, null=True, verbose_name='Order in which it will appear')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'db_table': 'faqs',
                'verbose_name': 'Faqs',
                'verbose_name_plural': 'Faqs',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link1', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.SmallIntegerField(blank=True, null=True, verbose_name='Order in which it will appear')),
                ('active', models.BooleanField(default=False, verbose_name='To be displayed or not')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'db_table': 'footer',
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filebrowser.fields.FileBrowseField(max_length=256)),
                ('object_id', models.PositiveIntegerField()),
                ('image_name', models.SmallIntegerField(blank=True, choices=[(1, 'Award1'), (2, 'Award2'), (3, 'Award3'), (4, 'Award4'), (5, 'Award5'), (6, 'Award6'), (7, 'Award7'), (8, 'Award8'), (9, 'Footer1'), (10, 'Footer2'), (11, 'Footer3'), (12, 'Footer4'), (13, 'Coverimage'), (14, 'Profileimage'), (15, 'landingpageimage')], help_text='Fill image name from the dropdown.', null=True)),
                ('image_a_name', models.CharField(blank=True, help_text='Fill actual image name.', max_length=50, null=True)),
                ('image_desc', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('cover_image', models.BooleanField(default=False, help_text='Only one of the image can be selected as cover image of the Photographer.', verbose_name='Cover Image')),
                ('profile_image', models.BooleanField(default=False, help_text='Only one of the image can be selected as profile image of the Photographer.', verbose_name='Profile Image')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'image',
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.City')),
            ],
            options={
                'db_table': 'locality',
                'verbose_name': 'Locality',
                'verbose_name_plural': 'Localities',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Key / Name of the Setting.', max_length=50, verbose_name='Settings Key')),
                ('value', models.CharField(blank=True, help_text='Value of the Setting.', max_length=50, null=True, verbose_name='Settings Value')),
                ('description', models.CharField(blank=True, help_text='Description of the Setting.', max_length=100, null=True, verbose_name='Settings Description')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'db_table': 'setting',
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Country')),
            ],
            options={
                'db_table': 'state',
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.State'),
        ),
    ]
