# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='priority',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Order in which it will appear'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Award1'), (2, 'Award2'), (3, 'Award3'), (4, 'Award4'), (5, 'Award5'), (6, 'Award6'), (7, 'Award7'), (8, 'Award8'), (9, 'Footer1'), (10, 'Footer2'), (11, 'Footer3'), (12, 'Footer4'), (13, 'Coverimage'), (14, 'Profileimage'), (15, 'landingpageimage')], help_text='Fill image name from the dropdown.', null=True),
        ),
    ]
