# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_footer_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='active',
            field=models.BooleanField(default=False, verbose_name='To be displayed or not'),
        ),
    ]
