# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_footer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_a_name',
            field=models.CharField(blank=True, help_text='Fill actual image name.', max_length=50, null=True),
        ),
    ]
