# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_image_image_a_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
