"""
Django settings for awards project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from os.path import abspath, dirname, basename, normpath, join

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROJECT_PATH = dirname(dirname(abspath(__file__)))

PROJECT_PATH_PARENT = dirname(dirname(dirname(abspath(__file__))))

# Project name.
PROJECT_NAME = basename(PROJECT_PATH)

# Absolute filesystem path to the top-level project folder.
PROJECT_ROOT = dirname(PROJECT_PATH)


# Add all necessary filesystem paths to our system path so that we can use
# python import statements.
sys.path.append(PROJECT_ROOT)

# STATIC_ROOT = normpath(join(PROJECT_PATH, 'static'))
STATIC_ROOT = os.path.join(PROJECT_PATH, 'static')
STATIC_URL = '/static/'

# Absolute filesystem path to the directory that will hold user-uploaded files.
# MEDIA_ROOT = normpath(join(PROJECT_PATH, 'media'))
# URL that handles the media served from MEDIA_ROOT.
# MEDIA_URL = '/media/'

STATIC_URL = '/static/'

# Absolute filesystem path to the directory that will hold user-uploaded files.
# MEDIA_ROOT = normpath(join(PROJECT_PATH, 'media'))
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(PROJECT_PATH, 'media')


# temp file upload dir
TEMP_UPLOAD_DIR = 'temp/'
FILEBROWSER_VERSION_BASEDIR = '_versions/'


# URL that handles the media served from MEDIA_ROOT.
UPLOAD_DEVICE_DIR = normpath('uploads/devices/')
UPLOAD_PHOTO_DIR = normpath('uploads/')
# UPLOAD_VENDOR_DIR = normpath('uploads/vendor/')
UPLOAD_FOOTER_DIR = normpath('uploads/footer/')
UPLOAD_PHOTOGRAPHER_DIR = normpath('uploads/photographer/')


AUTH_USER_MODEL = 'useraccount.UserProfile'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'g&m75fcwu@dk4ed2opcp6-j($yg0mrf=ma(*8q&e7%8r^21*rj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'grappelli',
    # for file uploads
    'filebrowser',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'useraccount',

    'compressor',
    # rest framework
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'awards.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["core/templates"],
        # 'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "core.context_processors.contextprocessor_samplelists",
            ],
        'loaders': [
           'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
        ],
        'debug': True

        },
    },
]

WSGI_APPLICATION = 'awards.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'awards',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {'autocommit': True, }
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.TemplateHTMLRenderer',
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    )
}

EMAIL_SITE_URL = 'http://www.awards.com'

#############File Browser settings

FILEBROWSER_EXTENSIONS = {"Image": []}

FILEBROWSER_VERSIONS = {
    # thumbnails for all the small listing displays
    'thumbnail': {'verbose_name': 'Thumbnail', 'width': 250, 'height': 160, 'opts': 'crop upscale'},
    # medium size for slider on detail page (contains watermark after verified)
    'medium': {'verbose_name': 'Medium', 'width': 720, 'height': 405, 'opts': 'crop upscale'},
    # # large size for zoomed view on detail page (contains watermark after verified)
    'large': {'verbose_name': 'Original', 'width': 1600, 'height': 1200, 'opts': 'upscale'},
    # original sized image just for backup.
    'original': {'verbose_name': 'Original', 'width': '', 'height': '', 'opts': ''},
    # logos small with no cropping
    'logo': {'verbose_name': 'Logo', 'width': '', 'height': 40, 'opts': ''},
}

FILEBROWSER_ADMIN_VERSIONS = ['thumbnail', 'large', 'medium', 'logo']
FILEBROWSER_ADMIN_THUMBNAIL = 'thumbnail'
FILEBROWSER_MAX_UPLOAD_SIZE = 5242880
# END FileBrowser

FILEBROWSER_DIRECTORY = "uploads/"
FILEBROWSER_VERSIONS_BASEDIR = '_versions/'
FILEBROWSER_MEDIA_ROOT=os.path.join(MEDIA_ROOT, 'uploads/')
FILEBROWSER_MEDIA_URL = MEDIA_URL + "uploads/"

# FILEBROWSER_URL_FILEBROWSER_MEDIA= MEDIA_URL + 'filebrowser/'
# FILEBROWSER_PATH_FILEBROWSER_MEDIA= os.path.join(MEDIA_ROOT, 'filebrowser/')

try:
    from awards.local_settings import *
except:
    pass
