# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='activate_photographer_page',
            field=models.BooleanField(default=False, help_text=b"Designates whether to show the photographer's profile on photographer page or not", verbose_name=b'If True, Profile will be seen on the photographer page'),
        ),
    ]
