# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_auto_20160417_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='priority',
            field=models.IntegerField(default=1, verbose_name=b'Home page profile visibility priority'),
        ),
    ]
